/**
 * Browser Supabase client.
 *
 * Uses only public, frontend-safe configuration:
 * NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY.
 *
 * The service-role key, the database password and any backend
 * secret must never appear here. Signed storage URLs are
 * generated by the backend after it verifies ownership, so the
 * frontend never needs privileged Supabase credentials.
 */
import { createClient } from "@supabase/supabase-js";
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
export const isSupabaseConfigured = Boolean(supabaseUrl && supabaseAnonKey);
export class SupabaseConfigurationError extends Error {
    constructor() {
        super("Supabase is not configured. Set NEXT_PUBLIC_SUPABASE_URL and " +
            "NEXT_PUBLIC_SUPABASE_ANON_KEY in frontend/.env.local.");
        this.name = "SupabaseConfigurationError";
    }
}
let browserClient = null;
/**
 * Return the shared browser client, creating it on first use.
 *
 * Creation is lazy so importing this module never throws and
 * `next build` succeeds before local environment values are
 * filled in. A missing configuration only fails at the moment
 * authentication is actually attempted, with a clear message.
 */
export function getSupabaseClient() {
    if (!supabaseUrl || !supabaseAnonKey) {
        throw new SupabaseConfigurationError();
    }
    if (!browserClient) {
        const isBrowser = typeof window !== "undefined";
        browserClient = createClient(supabaseUrl, supabaseAnonKey, {
            auth: {
                // Session storage only makes sense in the browser.
                // Disabling it on the server keeps rendering
                // side-effect free.
                persistSession: isBrowser,
                autoRefreshToken: isBrowser,
                detectSessionInUrl: isBrowser,
            },
        });
    }
    return browserClient;
}
